import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { products, getProduct, formatPrice } from "@/data/products";
import { ProductDetailClient } from "@/components/product-detail-client";
import { ProductCard } from "@/components/product-card";
import { siteConfig } from "@/config/site";
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProduct(slug);if(!p)return{};return{title:p.seoTitle,description:p.seoDescription,alternates:{canonical:`/products/${p.slug}`},openGraph:{title:p.seoTitle,description:p.seoDescription,images:[]}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=getProduct(slug);if(!product)notFound();const related=products.filter(p=>p.id!==product.id&&(p.category===product.category||p.ingredients.some(i=>product.ingredients.includes(i)))).slice(0,3);const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.name,description:product.description,sku:product.sku,image:product.images.map(x=>`${siteConfig.url}${x}`),brand:{"@type":"Brand",name:"DermaQ Max"},offers:{"@type":"Offer",priceCurrency:"INR",price:product.price,availability:"https://schema.org/InStock",url:`${siteConfig.url}/products/${product.slug}`}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="shell py-5 text-xs text-muted"><Link href="/">Home</Link> / <Link href="/shop">Shop</Link> / {product.name}</div><section className="shell pb-16"><ProductDetailClient product={product}/><div className="mt-16 grid gap-6 md:grid-cols-2"><Info title="Product highlights" items={product.features}/><Info title="Benefits" items={product.benefits}/><Info title="Key ingredients" items={product.ingredients}/><Info title="How to use" items={product.howToUse}/></div><div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="panel"><h2 className="text-xl font-bold text-navy">Who can use</h2><p className="mt-3 leading-7 text-muted">{product.whoCanUse}</p></div><div className="panel"><h2 className="text-xl font-bold text-navy">Product information</h2><p className="mt-3 leading-7 text-muted">SKU: {product.sku}<br/>Size: {product.size}<br/>MRP: {formatPrice(product.mrp)} inclusive of taxes</p></div><div className="panel"><h2 className="text-xl font-bold text-navy">Shipping & returns</h2><p className="mt-3 leading-7 text-muted">Free shipping above ₹499. See our shipping and return policies for current terms.</p></div></div><div className="mt-10 panel"><h2 className="text-2xl font-bold text-navy">Frequently asked</h2><details className="mt-5 border-t border-border py-4"><summary className="font-bold">Can I use this every day?</summary><p className="mt-3 text-muted">Use as directed on the pack. Patch test before first use and discontinue if irritation occurs.</p></details><details className="border-t border-border py-4"><summary className="font-bold">When will I see results?</summary><p className="mt-3 text-muted">Cosmetic experiences vary. Consistent use as directed is recommended; no medical outcome is promised.</p></details></div></section><section className="section bg-light"><div className="shell"><div className="section-head"><h2>You may also like</h2></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section></>}
function Info({title,items}:{title:string;items:string[]}){return <div className="panel"><h2 className="text-xl font-bold text-navy">{title}</h2><ul className="mt-4 grid gap-2">{items.map(x=><li className="flex gap-2 text-muted" key={x}><span className="text-aqua">●</span>{x}</li>)}</ul></div>}
