"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { formatPrice, products } from "@/data/products";
type Order={id:string;items:{productId:string;quantity:number}[];total:number;payment:string;address:string};
export default function OrderSuccess(){const [order,setOrder]=useState<Order|null>(null);// Browser-only demo order state is intentionally read after hydration.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{try{setOrder(JSON.parse(localStorage.getItem("dq-demo-order")||"null"))}catch{}},[]);return <section className="section"><div className="shell max-w-3xl"><div className="text-center"><CheckCircle2 className="mx-auto text-aqua" size={64}/><p className="eyebrow mt-5">Demo order created</p><h1 className="mt-2 text-4xl font-bold text-navy">Thank you for your order.</h1><p className="mt-3 text-muted">This is a local demonstration. No payment was taken and no order was sent to a fulfilment system.</p></div>{order&&<div className="panel mt-9"><div className="flex justify-between gap-3 border-b border-border pb-4"><span className="text-muted">Order ID</span><strong>{order.id}</strong></div><div className="mt-4 grid gap-3">{order.items.map(i=>{const p=products.find(x=>x.id===i.productId);return p?<div className="flex justify-between" key={p.id}><span>{p.name} × {i.quantity}</span><strong>{formatPrice(p.price*i.quantity)}</strong></div>:null})}</div><div className="mt-5 flex justify-between border-t border-border pt-4 text-xl font-bold text-navy"><span>Total</span><span>{formatPrice(order.total)}</span></div><p className="mt-5 text-sm text-muted"><strong>Payment:</strong> {order.payment.toUpperCase()}<br/><strong>Ship to:</strong> {order.address}</p></div>}<div className="mt-7 flex flex-wrap justify-center gap-3"><Link className="btn-secondary" href="/track-order">Track order</Link><Link className="btn-primary" href="/shop">Continue shopping</Link></div></div></section>}
