import Link from "next/link";
import { ArrowDown, BadgeCheck, Beaker, CloudSun, Droplets, FlaskConical, Leaf, ShieldCheck, Sparkles, Sun, Wind } from "lucide-react";
import { claimFlags } from "@/config/site";
import { formatPrice, products } from "@/data/products";
import { ProductArt } from "@/components/product-art";
import { ProductCard } from "@/components/product-card";

const categories = [
  ["Sun Protection", "Daily defence, weightless feel", Sun, "Sun Protection"], ["Face Care", "Cleanse without compromise", Droplets, "Skin Care"], ["Scalp Care", "Clear, comfortable scalp care", Wind, "Hair Care"], ["Moisturizers", "Barrier-first hydration", CloudSun, "Skin Care"], ["Lip Care", "Moisture meets UV care", Sparkles, "Lip Care"], ["Combos", "Routines that work together", Beaker, "Combos"]
] as const;
const ingredients = [
  ["Niacinamide", "Supports an even-looking tone and balanced skin."], ["Hyaluronic Acid", "Draws moisture to help skin feel hydrated."], ["Ceramides", "Lipids that support the skin barrier."], ["Cica Extract", "Helps comfort and soothe skin."], ["Piroctone Olamine", "A cosmetic scalp-care active for visible flakes."], ["Aloe Vera", "A refreshing, soothing botanical."], ["Vitamin E", "An antioxidant used in nourishing care."], ["Zinc PCA", "Helps support a balanced-feeling scalp."], ["Shea Butter", "Rich emollient for soft, comfortable lips."], ["Tea Tree Oil", "A botanical used in fresh scalp-care formulas."]
];

export default function Home() {
  const sunscreen = products[0];
  return <>
    <section className="hero"><div className="shell grid min-h-[680px] items-center gap-10 py-14 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div><p className="eyebrow">Advanced skin & scalp science</p><h1>Science for<br/><span>healthier skin.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">Advanced everyday skin and scalp care, designed for the Indian climate.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary btn-lg" href="/shop">Shop now</Link><Link className="btn-secondary btn-lg" href="#bestsellers">Explore products</Link></div><div className="mt-10 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4">{[...(claimFlags.dermatologicallyTested ? [[BadgeCheck, "Dermatologically Tested"]] : []), [Droplets, "Everyday comfort"], [FlaskConical, "Science-led formulas"], [Sun, "Indian climate focus"]].map(([Icon, label]) => <div className="trust" key={String(label)}><Icon size={20}/><span>{String(label)}</span></div>)}</div></div><div className="hero-visual"><span className="formula-note top-[12%] left-[4%]">NIACINAMIDE</span><span className="formula-note right-[3%] bottom-[18%]">AQUA GEL</span><ProductArt src={sunscreen.images[0]} name={sunscreen.name} priority /></div></div></section>
    <section className="offer-section"><div className="shell py-16"><div className="offer-card grid items-center gap-8 p-7 md:p-12 lg:grid-cols-[.8fr_1.2fr_.8fr]"><div><p className="eyebrow text-aqua">Special offer</p><h2 className="mt-2 text-5xl font-black uppercase leading-[.9] text-white md:text-7xl">Buy 1<br/>Get 1<br/><span>Free</span></h2><p className="mt-5 text-white/70">DermaQ Max Sunscreen<br/>SPF 50+ PA++++ · 2 × 50 ml</p></div><div className="relative mx-auto flex w-full max-w-md items-end justify-center"><div className="w-2/3 -rotate-6"><ProductArt src={sunscreen.images[0]} name={sunscreen.name} /></div><div className="-ml-24 w-2/3 rotate-6"><ProductArt src={sunscreen.images[0]} name={sunscreen.name} /></div></div><div className="rounded-sm border border-white/15 bg-white/8 p-6"><p className="text-sm text-white/50">MRP <del>{formatPrice(1200)}</del></p><p className="mt-3 text-sm uppercase tracking-widest text-aqua">Offer price</p><p className="text-5xl font-bold text-white">₹600</p><p className="mt-2 text-sm font-semibold text-aqua">You save ₹600</p><Link className="btn-light mt-6 w-full" href={`/products/${sunscreen.slug}`}>Grab the offer</Link><p className="mt-3 text-center text-xs text-white/45">Add 2 units to cart. Offer applies automatically.</p></div></div></div></section>
    <section id="bestsellers" className="section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Everyday essentials</p><h2>Our bestsellers</h2></div><Link className="text-link" href="/shop">View all products</Link></div><div className="product-grid">{products.slice(0,4).map((p) => <ProductCard key={p.id} product={p}/>)}</div></div></section>
    <section className="section bg-light"><div className="shell"><div className="section-head"><div><p className="eyebrow">Find your fit</p><h2>Shop by category</h2></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(([name, desc, Icon, filter]) => <Link key={name} href={`/shop?category=${encodeURIComponent(filter)}`} className="category-card"><div className="category-icon"><Icon /></div><div><h3>{name}</h3><p>{desc}</p></div></Link>)}</div><div className="mt-14"><p className="eyebrow">Shop by concern</p><div className="mt-4 flex flex-wrap gap-2">{["Sun Protection", "Dry Skin", "Oily Skin", "Skin Barrier", "Dandruff", "Itchy Scalp", "Lip Care"].map((x) => <Link className="concern-chip" href={`/shop?concern=${encodeURIComponent(x)}`} key={x}>{x}</Link>)}</div></div></div></section>
    <section id="why" className="section"><div className="shell"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Why DermaQ Max?</p><h2 className="mt-2">Science-led everyday care.</h2></div><div className="mt-10 grid gap-px overflow-hidden rounded-sm border border-border bg-border md:grid-cols-4">{[[FlaskConical,"Dermatology inspired","Thoughtfully designed skincare and scalp-care formulations."],[ShieldCheck,"Skin-first formulations","Focused on everyday skin and scalp needs."],[Droplets,"Lightweight formulas","Designed for comfortable everyday use."],[Sun,"Made for Indian climate","Developed with Indian consumers and climate conditions in mind."]].map(([Icon,title,copy]) => <article className="why-card" key={String(title)}><Icon/><h3>{String(title)}</h3><p>{String(copy)}</p></article>)}</div></div></section>
    <section id="ingredients" className="section ingredient-section"><div className="shell"><div className="section-head"><div><p className="eyebrow text-aqua">Ingredient library</p><h2 className="text-white">The science inside</h2></div></div><div className="ingredient-grid">{ingredients.map(([name, copy], i) => <article className="ingredient-card" key={name}><span>{String(i+1).padStart(2,"0")}</span><div className="ingredient-symbol"><Leaf/></div><h3>{name}</h3><p>{copy}</p><Link href={`/shop?q=${encodeURIComponent(name)}`}>View products</Link></article>)}</div></div></section>
    <section className="section"><div className="shell grid items-center gap-12 lg:grid-cols-2"><div><p className="eyebrow">Simple. Consistent. Effective.</p><h2 className="mt-2">Build your daily routine</h2><p className="mt-4 max-w-lg text-muted">Three comfortable steps for a calm, protected start to the day.</p></div><div className="routine">{[["01","Cleanse","Gentle Foaming Face Wash"],["02","Moisturize","Barrier Repair Moisturizer"],["03","Protect","SPF 50+ Sunscreen"]].map(([n,title,product],i) => <div key={n}>{i>0 && <ArrowDown className="routine-arrow"/>}<article className="routine-step"><span>{n}</span><div><p>{title}</p><h3>{product}</h3></div></article></div>)}</div></div></section>
    <section className="section bg-light"><div className="shell"><div className="section-head"><div><p className="eyebrow">Community notes</p><h2>Reviews, transparently shown</h2></div><button className="btn-secondary" disabled>Write a review</button></div><div className="panel"><p className="font-bold text-navy">No verified customer reviews yet.</p><p className="mt-2 text-sm leading-6 text-muted">The review interface is ready for a verified-purchase backend. We do not display fabricated customer testimonials; development sample data is intentionally excluded from the live interface.</p></div></div></section>
  </>;
}

