"use client";
import { useMemo, useState } from "react";
import { SlidersHorizontal, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { products } from "@/data/products";
import { ProductCard } from "@/components/product-card";

export function ShopClient() {
  const params = useSearchParams(); const [mobileFilters, setMobileFilters] = useState(false); const [category, setCategory] = useState(params.get("category") || ""); const [concern, setConcern] = useState(params.get("concern") || ""); const [sort, setSort] = useState("featured"); const [maxPrice, setMaxPrice] = useState(700);
  const q = (params.get("q") || "").toLowerCase();
  const visible = useMemo(() => products.filter((p) => (!category || p.category === category) && (!concern || p.concerns.includes(concern)) && p.price <= maxPrice && (!q || [p.name,p.category,...p.ingredients,...p.concerns].join(" ").toLowerCase().includes(q))).sort((a,b) => sort === "low" ? a.price-b.price : sort === "high" ? b.price-a.price : sort === "new" ? Number(b.newArrival)-Number(a.newArrival) : sort === "best" ? Number(b.bestSeller)-Number(a.bestSeller) : Number(b.featured)-Number(a.featured)), [category,concern,maxPrice,q,sort]);
  const filters = <div className="grid gap-7"><div><label className="font-bold text-navy">Category</label><div className="mt-3 grid gap-2">{["","Skin Care","Hair Care","Sun Protection","Lip Care","Combos"].map(x => <label className="flex gap-2 text-sm text-muted" key={x || "all"}><input type="radio" name="category" checked={category===x} onChange={() => setCategory(x)}/>{x || "All products"}</label>)}</div></div><div><label className="font-bold text-navy">Concern</label><select className="input mt-3" value={concern} onChange={e => setConcern(e.target.value)}><option value="">All concerns</option>{["Sun Protection","Dry Skin","Oily Skin","Skin Barrier","Dandruff","Itchy Scalp","Lip Care"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className="font-bold text-navy">Price up to ₹{maxPrice}</label><input className="mt-3 w-full accent-[var(--blue)]" type="range" min="250" max="700" step="50" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></div><button className="btn-secondary" onClick={() => { setCategory("");setConcern("");setMaxPrice(700); }}>Clear filters</button></div>;
  return <section className="section"><div className="shell"><div className="mb-6 flex items-center justify-between gap-3"><p className="text-sm text-muted">{visible.length} products</p><div className="flex gap-2"><button className="btn-secondary lg:hidden" onClick={()=>setMobileFilters(true)}><SlidersHorizontal size={17}/> Filters</button><select className="input max-w-[210px]" aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="best">Best selling</option><option value="new">Newest</option><option value="low">Price low to high</option><option value="high">Price high to low</option></select></div></div><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="hidden border-r border-border pr-7 lg:block">{filters}</aside><div>{visible.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div> : <div className="empty"><h2 className="text-2xl font-bold text-navy">No products found</h2><p className="mt-2 text-muted">Try clearing a filter or choosing another concern.</p></div>}</div></div></div>{mobileFilters && <div className="mobile-overlay" onClick={()=>setMobileFilters(false)}><aside className="mobile-menu" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><strong className="text-xl text-navy">Filters</strong><button className="icon-btn" onClick={()=>setMobileFilters(false)}><X/></button></div><div className="mt-7">{filters}</div></aside></div>}</section>;
}

